name: Hello PR

on:
  pull_request:

run-name: pythonPR

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python main.py